### ISSUE TITLE
Circular JSON? Changing Direction

### ISSUE THREAD

**Issue by rdemo** [ssshooter/mind-elixir-core#216]
When using the toolbar to change direction, I'm getting this error in the console:

Uncaught SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at $.Ot [as refresh] (MindElixir.js:953:1)
    at $.$t [as initRight] (MindElixir.js:944:1)
    at i.onclick (MindElixir.js:835:1)
Ot @ MindElixir.js:953
$t @ MindElixir.js:944
i.onclick @ MindElixir.js:835

Working with MindElixir.js I see that when it gets to the "refresh" function "Ot" that "e" is undefined

I've taken it back to the bare bones example and am still having this issue. Ideas?

**Comment by rdemo** [comment]
I went back to version 2.1.0 to get this to work.

Any call to .refresh() in version 3 and above have the "undefined" error above.  As info.
