### ISSUE TITLE
好像对webcomponent支持不好

### ISSUE THREAD

**Issue by nickolboy** [SSShooter/mind-elixir-core#224]
样式没有加载到webcomponent内
另外还有报错：

```
MindElixir.js:1931 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nodeObj')
    at qe (MindElixir.js:1931:82)
    at MindElixir.js:1971:5
    at Proxy.forEach (<anonymous>)
    at Proxy.Rn (MindElixir.js:1970:50)
    at Proxy.mt (MindElixir.js:436:8)
    at Proxy.init (MindElixir.js:2039:471)
    at Mindmap.ce.vue:14:3
    at runtime-core.esm-bundler.js:2675:88
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
```

**Comment by ssshooter** [comment]
暂时没有研究 web component……
