### ISSUE TITLE
回车创建新节点之后使用undo功能报错，版本4.0.5

### ISSUE THREAD

**Issue by JasionM** [SSShooter/mind-elixir-core#274]
Uncaught Error: FindEle: Node 1c6899228a77061d not found, maybe it's collapsed.
    at C (/node_modules/mind-elixir/dist/MindElixir.js:401:19)
    at Mt.e.undo (/node_modules/mind-elixir/dist/MindElixir.js:1238:85)
    at HTMLDivElement.eval (/node_modules/mind-elixir/dist/MindElixir.js:1251:121)

**Comment by SSShooter** [comment]
能否提供一下重现链接？

**Comment by JasionM** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JasionM** [comment]
就是创建完新节点之后，执行undo回退，就会报错，3.0.4之后的版本好像就有问题了，好像是回退的操作里面会调用selectNode方法，但是因为回退创建逻辑时，那个节点已经没了，然后调用selectNode就报错了

**Comment by SSShooter** [comment]
明白了，谢谢反馈
